### ISSUE TITLE
Can anyone please help me with this

### ISSUE THREAD

**Issue by sampathsahukara** [Gr1mmie/Practical-Ethical-Hacking-Resources#11]
I'm using ALFA AWUS1900 Adapter and I'm changing it into 
monitor mode using iwconfig and it's working in monitor mode in wlan0 interface..
.
.
When I'm trying in 
airmon-ng start wlan0

****its showing like this****

Newly created monitor mode interface is *NOT* in monitor mode.
Removing non-monitor wlan0mon interface..
Segmentation fault
 

What to do please  help

I want it into mon0 or wlan0mon

Because in wash --interface it's not working with wlan0

Please help 😔😕😕😕😕

**Comment by Gr1mmie** [comment]
This is the repo for the course resources. If you have any questions regarding the course, your best bet is to join the discord server, we would be able to better help you there. There should be a link to the server under general links.
